"""Added profile fields

Revision ID: 8a403b6d2ae1
Revises: c593fde5d98a
Create Date: 2026-07-30 02:42:52.959035

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a403b6d2ae1'
down_revision = 'c593fde5d98a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('bio', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('skills', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('github', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('linkedin', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('linkedin')
        batch_op.drop_column('github')
        batch_op.drop_column('skills')
        batch_op.drop_column('bio')
        batch_op.drop_column('phone')

    # ### end Alembic commands ###
