"""Complete placement model

Revision ID: 9a866dd2d2d1
Revises: 8a403b6d2ae1
Create Date: 2026-07-30 03:11:51.625611

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a866dd2d2d1'
down_revision = '8a403b6d2ae1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('placements', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('role', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('package', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('location', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('eligibility', sa.String(length=150), nullable=False))
        batch_op.add_column(sa.Column('deadline', sa.Date(), nullable=False))
        batch_op.add_column(sa.Column('apply_link', sa.String(length=500), nullable=False))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('placements', schema=None) as batch_op:
        batch_op.drop_column('created_at')
        batch_op.drop_column('apply_link')
        batch_op.drop_column('deadline')
        batch_op.drop_column('eligibility')
        batch_op.drop_column('location')
        batch_op.drop_column('package')
        batch_op.drop_column('role')
        batch_op.drop_column('company')

    # ### end Alembic commands ###
