"""Create events table

Revision ID: ade92238b0f6
Revises: 9a866dd2d2d1
Create Date: 2026-07-31 18:59:34.667156

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ade92238b0f6'
down_revision = '9a866dd2d2d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('event_date', sa.String(length=50), nullable=False),
    sa.Column('event_time', sa.String(length=30), nullable=False),
    sa.Column('venue', sa.String(length=150), nullable=False),
    sa.Column('organizer', sa.String(length=150), nullable=False),
    sa.Column('registration_link', sa.String(length=500), nullable=True),
    sa.Column('poster', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    op.drop_table('events')
    # ### end Alembic commands ###
