"""Added  enrollment number

Revision ID: ba501bd07a84
Revises: 46216595c879
Create Date: 2026-07-29 22:05:00.948541

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba501bd07a84'
down_revision = '46216595c879'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('enrollment', sa.String(length=30), nullable=False))
        batch_op.create_unique_constraint(None, ['enrollment'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('enrollment')

    # ### end Alembic commands ###
