"""Updated Note model

Revision ID: c593fde5d98a
Revises: 26ccf1cd47ef
Create Date: 2026-07-30 02:07:08.628011

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c593fde5d98a'
down_revision = '26ccf1cd47ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=150), nullable=False))
        batch_op.add_column(sa.Column('subject', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('department', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('year', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('file_name', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('uploaded_by', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.drop_column('created_at')
        batch_op.drop_column('uploaded_by')
        batch_op.drop_column('file_name')
        batch_op.drop_column('year')
        batch_op.drop_column('department')
        batch_op.drop_column('subject')
        batch_op.drop_column('title')

    # ### end Alembic commands ###
